name: segretaria_virtuale
description: "La tua assistente personale digitale"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.0
  oauth2: ^2.0.2
  flutter_appauth: ^6.0.2
  speech_to_text: ^6.1.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.1.5
  table_calendar: ^3.0.9
  intl: any
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar: ^25.2.3
  flutter_timeline_calendar: ^1.0.9
  http: ^1.1.0
  font_awesome_flutter: ^10.6.0
  timezone: ^0.9.2
  uuid: ^4.1.0
  url_launcher: ^6.2.1

  # Aggiungi queste due dipendenze
  fl_chart: ^0.66.0
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Aggiungi questa sezione se hai asset
  assets:
    - assets/images/
    - assets/icons/

  # Configurazione font personalizzati (opzionale)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700